### PR TITLE
Refactor web debugging into scriptlet

### PR DESCRIPTION
**Pull request by kiesel**
Port of xp-framework/xp-framework#370

### CODE REVIEW

**Comment by thekid** [comment]
The failing test:

```sh
F unittest.TestAssertionFailed(test= scriptlet.unittest.XmlScriptletTest::defaultParameters, time= 0.003 seconds) {
  unittest.AssertionFailedError{ expected ["...xp..."] but was ["......"] using: 'equals' }
  ...
}
``` 

Was fixed back in @4f50885a6ae5eef3c3f6085d830d9a90e9046723; seems your branch is based on an older checkout

**Comment by kiesel** [comment]
I'm puzzled; I branched today and 4f50885a6ae5eef3c3f6085d830d9a90e9046723 is part of the branch.

**Comment by thekid** [comment]
Sorry, it seems @9e3aba042c8127229c02fe2f37d5d57efbcb7805 also needs to be merged (which was done on a branch). No idea why this hasn't surfaced before...

**Comment by thekid** [comment]
I'd clearly prefer a solution based on scriptlet filters. As a rule of thumb: I'd like to reduce a `Scriptlet` down to an interface a simple as:

```php
interface Scriptlet {
  public function service($request, $response);
}
```

A scriptlet filter would be reusable without needing to subclass (and then potentially again having overwrite parts of) a base class you'd create with your favorite `trace()` implementation. Sure, you could create a trait... Here goes my suggestion:

```php
class TraceFilter extends \lang\Object implements \scriptlet\Filter {
  private $flags= 0;

  public function filter($request, $response, $invocation) {
    try {
      $r= $invocation->proceed($request, $response);
      if (false === $r) return false;  // E.g. redirects

      if ($this->flags & WebDebug::ERRORS) {
        // ...Show \xp::$errors
      }
    } catch (Throwable $e) {
      if ($this->flags & WebDebug::EXCEPTIONS) {
        // ... Show exception
      }
      throw $e;
    }
  }
}
```

The benefit here is that the request parameters could also be accessed, which might be beneficial in understanding the exception. Or we store the last response in the session and then access it in-page via XHR. Or we add it to the headers. Or... well. You get the point.

**Comment by thekid** [comment]
Filters have been merged (see #3).

**Pull request closed without merging**
